---
- name: date_time_demp
  hosts: localhost
  gather_facts: true
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: DateTime_1
      ansible.builtin.debug:
