---
- name: selecterFillter
  hosts: localhost
  gather_facts: true
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: filterS
      ansible.builtin.debug:
        var: "ansible_facts.eth1.features"
    - name: filter_Enable
      ansible.builtin.debug:
        msg: "{{( ansible_facts.eth1.features | dict2items | selectattr('value', 'match', 'on') )}}"
