---
- name: task Demo
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    mypath: "/home/rej/Ansible/TMP"
    resultpath: ""

  tasks:
    - name: find_files
      ansible.builtin.find:
        paths: "{{mypath}}"
        age: 1m
        patterns: "*.logxx"
        recurse: yes
      register: files_to_copy

    - copy: 
         src: "{{ item.path }}" 
         dest: /home/rej/Ansible/temp2
         owner: root
         mode: 0775
      loop: "{{ files_to_copy.files }}"  

---
- hosts: linux
  become: yes
  tasks:
    - name: find the zip files
      find:
        paths: "/home"
        recurse: no
        patterns: "*.logxx"
      register: zip_files
    - name: copy the zip files
      fetch:
        src: "{{ item.path }}"
        dest: "/home/rej/Ansible/temp2/"
        flat: yes
      with_items: "{{ zip_files.files }}"
      register: zip_status
      delegate_to: localhost
