---
- hosts: app
  gather_facts: true
  tasks:
    - name: Fetch the file from the mwiapp01 to master
      run_once: yes
      fetch: src=/home/linuxmini1/tmp/test2.zip dest=buffer/ flat=yes
      when: "{{ inventory_hostname == 'linuxmini1' }}"

    - name: Copy the file from master to mwiapp02
      copy: src=buffer/test2.zip dest=/home/linuxmini1/tmp/
      when: "{{ inventory_hostname == 'linuxmini2' }}"