---
- name: internalVariable
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: internalVariable
      ansible.builtin.debug:
       var: "{{ item }}"
      loop: 
       - ansible_config_file
       - playbook_dir
      
