# code: language=ansible
---
- name: rootLoginenable
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: rootLoginenable1
      ansible.builtin.lineinfile:
       dest: /etc/ssh/sshd_config
       regexp: '^PermitRootLogin'
       line: "PermitRootLogin yes"
       state: present
      notify: ssh restart

  handlers: ssh restart
  - name: ssh restart
    ansible.builtin.service:
     name: sshd
     state: restarted

